on:
  pull_request:
  push:
    branches:
      - main
      - try/**
    tags-ignore:
      - v*.*.*

name: Tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx pnpm it

